FROM mysql:8.4

# ENV MYSQL_ROOT_PASSWORD=root
# ENV MYSQL_DATABASE=laravel
# ENV MYSQL_USER=laravel
# ENV MYSQL_PASSWORD=laravel

# نسخ ملف الإعداد
COPY ./docker/mysql/conf.d /etc/mysql/conf.d

EXPOSE 3306
